---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    name: mongodb
  clusterIP: None # headless service
  selector:
    name: mongodb
    tier: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    matchLabels:
       name: mongodb
       tier: db
  serviceName: "mongodb"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        name: mongodb # has to match .spec.selector.matchLabels
        tier: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: sahiya/mongodb:v2
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-volume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: mongodb-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "efs-sc"
      resources:
        requests:
          storage: 1Gi  